services:

  backend:
    build: ./backend
    image: backend_car_rental
    container_name: backend_car_rental
    restart: always
    volumes:
      - ./backend/app:/backend/app
      - ./backend/scripts:/backend/scripts
    ports:
      - "8000:80"
    entrypoint: ["/backend/entrypoint.sh"]

  db:
    image: mysql:9.3.0
    container_name: mysql_car_rental
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer_car_rental
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
    driver: local